name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # change if your default branch is 'master' or something else

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js site (static export)
        run: yarn build

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: out

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
